server:
  port: 8080
spring:
  profiles:
    active: dev
---
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/passgen;MODE=MySQL;DB_CLOSE_DELAY=-1;
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: dev
#logging:
#  level:
#    org.springframework: 'DEBUG'
---
## Add more profiles here for production... mode